### ISSUE TITLE
disconf2.3.26不兼容spring5.0以上版本 怎么办

### ISSUE THREAD

**Issue by tonyhezero** [xjzrc/disconf-spring-boot-starter#1]
java.lang.NoSuchMethodError: com.baidu.disconf.client.addons.properties.DefaultPropertyPlaceholderConfigurer.parseStringValue(Ljava/lang/String;Ljava/util/Properties;Ljava/util/Set;)Ljava/lang/String;
	at com.baidu.disconf.client.addons.properties.ReloadingPropertyPlaceholderConfigurer.parseStringValue(ReloadingPropertyPlaceholderConfigurer.java:97)
	at com.baidu.disconf.client.addons.properties.ReloadingPropertyPlaceholderConfigurer$PlaceholderResolvingBeanDefinitionVisitor.resolveStringValue(ReloadingPropertyPlaceholderConfigurer.java:457)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanClassName(BeanDefinitionVisitor.java:107)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanDefinition(BeanDefinitionVisitor.java:80)
	at com.baidu.disconf.client.addons.properties.ReloadingPropertyPlaceholderConfigurer.processProperties(ReloadingPropertyPlaceholderConfigurer.java:382)
	at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:86)

**Comment by xjzrc** [comment]
看了下disconf源码，问题是disconf调用了Spring4过时的API，到了Spring5，这个API直接被干掉了。
有人已经在disconf项目中给出了解决方法：https://github.com/knightliao/disconf/issues/373

**Comment by tonyhezero** [comment]
@xjzrc  ok,谢谢

**Comment by liusongshan** [comment]
@xjzrc 已经降级，谢谢了！！
